version: '3.8'

services:
  db:
    container_name: db_univmedica
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: universal_medica
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root

  web:
    build: php
    container_name: www_univ_medica
    ports:
      - "8080:80"
    volumes:
      - ./php/apache:/etc/apache2/sites-enabled
      - ./:/var/www
